### ISSUE TITLE
Unhandled exception. System.ArgumentException: Open generic service type 'Microsoft.Extensions.Options.IOptions`1[TOptions]' requires registering an open generic implementation type.  (Parameter 'descriptors')

### ISSUE THREAD

**Issue by unlimitedcoder2** [enisn/DotNurseInjector#6]
I am trying to add the dot nurse injector to my project but it fails when I try to start the server and has this error.

```
Unhandled exception. System.ArgumentException: Open generic service type 'Microsoft.Extensions.Options.IOptions`1[TOptions]' requires registering an open generic implementation type.
 (Parameter 'descriptors')
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at DotNurse.Injector.DotNurseServiceProvider..ctor(IServiceCollection defaultServiceCollection)
   at DotNurse.Injector.DotNurseServiceProviderFactory.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateBuilder(IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at backend.Program.Main(String[] args) in C:\Users\Alex\source\repos\cloudpc\backend\backend\Program.cs:line 16
```

**Comment by enisn** [comment]
Can you share your implementation codo sections such as **Program.cs** & **Startup.cs**

**Comment by unlimitedcoder2** [comment]
I just did what you said to do [here](https://stackoverflow.com/a/64620777)

**Comment by enisn** [comment]
I think the problem occurs while resolving `IOptions<T>`.

**Comment by enisn** [comment]
@pharazfadaei

I think `IOptions<T>` & other generic services weren't handled in PR #4
